import Layout from "@/layouts";
import Head from "next/head";
import Link from "next/link";
export default function Home() {
    return (
        <>
            <Head>
                <title>E Commerce</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <main className={"container mx-auto"}>
                    <Link href={"/category"}>Go To Category</Link>
                </main>
            </Layout>
        </>
    );
}
